### ISSUE TITLE
Shibboleth2 in Gluu CE 2.4.4 fails to start in case wrong xml passed as metadata for any active TR

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxIdp#8]
I encountered it while solving an issue in instance built from latest CE 2.4.4 package.

One TR was configured to fetch metadata from url. At some point in time requesting this url started to result in bad formatted xml (actually, it wasn't xml at all). When after this I tried to restart tomcat, Shibboleth failed to start with next java exception appearing in `idp-process.log` (please see full text [here](https://github.com/GluuFederation/oxIdp/files/528304/shib-failure-wrong-xml-md.txt)):

```
3:54:21.610 - INFO [edu.internet2.middleware.shibboleth.common.config.security.ShibbolethSecurityPolicyBeanDefinitionParser:59] - Parsing configuration for SecurityPolicyType security policy with id: shibboleth.SAML2SLOSecurityPolicy
13:54:21.876 - ERROR [org.opensaml.xml.parse.StaticBasicParserPool:50] - XML Parsing Error
org.xml.sax.SAXParseException: Content is not allowed in prolog.
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198) ~[na:1.7.0_95]
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177) ~[na:1.7.0_95]
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400) [na:1.7.0_95]

...

13:54:21.880 - ERROR [org.opensaml.saml2.metadata.provider.AbstractReloadingMetadataProvider:315] - Unable to unmarshall metadata
org.opensaml.xml.io.UnmarshallingException: org.opensaml.xml.parse.XMLParserException: Invalid XML
    at org.opensaml.saml2.metadata.provider.AbstractMetadataProvider.unmarshallMetadata(AbstractMetadataProvider.java:473) [opensaml-2.6.6.jar:na]
    at org.opensaml.saml2.metadata.provider.AbstractReloadingMetadataProvider.unmarshallMetadata(AbstractReloadingMetadataProvider.java:312) [opensaml-2.6.6.jar:na]
    at org.opensaml.saml2.metadata.provider.AbstractReloadingMetadataProvider.processNewMetadata(AbstractReloadingMetadataProvider.java:353) [opensaml-2.6.6.jar:na]

...

Caused by: org.opensaml.xml.parse.XMLParserException: Invalid XML
    at org.opensaml.xml.parse.StaticBasicParserPool.parse(StaticBasicParserPool.java:243) ~[xmltooling-1.4.6.jar:na]
    at org.opensaml.saml2.metadata.provider.AbstractMetadataProvider.unmarshallMetadata(AbstractMetadataProvider.java:460) [opensaml-2.6.6.jar:na]
    ... 62 common frames omitted
Caused by: org.xml.sax.SAXParseException: Content is not allowed in prolog.
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198) ~[na:1.7.0_95]
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177) ~[na:1.7.0_95]

...
```

The issue was resolved by deactivating this TR via web UI (oxTrust started successfully), but still it doesn't seem to me as proper handling of such minor issue (all TRs are non-operational because of one of them got wrong metadata). Can it be configured to at least not fail in case some metadata can't be parsed?

**Comment by aliaksander-samuseu** [comment]
Why I think it may be possible is because of this log entry:

```
13:54:21.887 - ERROR [org.opensaml.saml2.metadata.provider.AbstractMetadataProvider:411] - Metadata provider failed to properly initialize, fail-fast=true, halting
```

I also saw a couple of posts on forums hinting that it's possible (or was possible before)

**Comment by yurem** [comment]
Can we close it. Is it part of CE 3.0.0?

**Comment by yurem** [comment]
It's related to old IDP version
